### ISSUE TITLE
Please fix issues reported by adapter checker

### ISSUE THREAD

**Issue by mcm1957** [foxthefox/ioBroker.jeelink#161]
❗ **[E140] width and height of logo are not equal**
 👀 [W171] "common.title" is deprecated in [io-package.json](https://github.com/foxthefox/ioBroker.jeelink/blob/master/io-package.json

Note: a fix with next release is sufficient - not blocking for stable

**Comment by foxthefox** [comment]
it is off by 2 pixel, OK I will make it identical

**Comment by mcm1957** [comment]
Its low prior...
Checker does not have a tolerance window - maybe we should enhance it - if theres time :-)

**Comment by foxthefox** [comment]
done
