### ISSUE TITLE
Lacrosse DTT produces warnings over 50° Celsius

### ISSUE THREAD

**Issue by Thomas-8-Bit** [foxthefox/ioBroker.jeelink#57]
The Lacrosse DTT sensor delivers temperatures up to 60° Celsius but the adapter doesn't write them to the object. It produces warnings in the log, that temperature must be 50° maximum. Can you correct that?

**Comment by foxthefox** [comment]
I will fix it tomorrow.

**Comment by foxthefox** [comment]
you can try the github repo,
after installation:
stop the adapter
please delete at least the temperature datapoint, otherwise the new settings are not effective
start the asapter
