### ISSUE TITLE
Datenerfassung bricht nach einer Weile ab

### ISSUE THREAD

**Issue by PrinzEisenherz1** [foxthefox/ioBroker.jeelink#91]
Moin.
Ich lese mit Hilfe des jeelink-Adapters mehrere Technoline DTT und DTH's aus.
Funktioniert soweit auch wunderbar.
Stelle ich das LogLevel des Adapters auf error bzw warning dann werden nach einer Weile keine Daten mehr erfasst.
Zumindest ist mir das jetzt beim DTT aufgefallen.
Stelle ich das LogLevel wieder auf Info, dann läuft alles ohne Probleme.
Ich würde aber gerne das LogLevel auf error stellen, da mir sonst der Adapter das Logfile zumüllt.

Meine Adapterversion ist 1.0.3

Gruß
Johnny

**Comment by foxthefox** [comment]
Sorry für die späte Antwort, war im Urlaub. Werde mir das Problem dieses WE mal anschauen.
Ansich dürfte das loglevel keinen Einfluß haben, 
evtl. sollte ich ja auch ein paar infos in debug rübernehmen, wenn das zuviel ist

**Comment by foxthefox** [comment]
habe auf github die Version 1.1.1 erstellt, bitte einmal testen und berichten.
Ich habe diverse loglevel geändert, so daß es bei info nur noch nach dem Start diverse Infos gibt. Das sollte helfen den Adapter im "info" lassen zu können. Warum es in anderen loglevel abbricht, ist mir bis jetzt nicht klar, woran das liegen soll.
