### ISSUE TITLE
Adapter zeigt im ioBroker keine Daten der Sensoren an

### ISSUE THREAD

**Issue by tis-cs** [foxthefox/ioBroker.jeelink#92]
**Describe the bug**  
Adapter empfängt keine H/T Daten von einem TX29DTH-IT

**To Reproduce**  
1. Adapter auf /dev/ttyUSB0 mit Baud 57600 konfiguriert und gestartet
2. In den Protokollen für den Adapter jeelink.0 geschaut (alle Modi getestet debug/info/warn/silly)
3. keine Daten von den Sensoren zu sehen

**Expected behavior**  
Sensordaten im DTH Format als undefiniert

**Screenshots & Logfiles**  
per Console läuft der Stick

`pi@iobroker-slave:~ $ sudo -u iobroker cat /dev/ttyUSB0`
`OK 9 35 1 4 196 50`
`OK 9 35 1 4 197 50`

Der Adapter kann auch drauf zugreifen

`pi@iobroker-slave:~ $ sudo lsof /dev/ttyUSB0`
`COMMAND     PID     USER   FD   TYPE DEVICE SIZE/OFF NODE NAME`
`io.jeelin 17540 iobroker   32uW  CHR  188,0      0t0  252 /dev/ttyUSB0`

**Versions:**  
 - Adapter version: 1.1.0 und 0.1.4 getestet
 - JS-Controller version: 4.0.23
 - Node version: 16.18.1
 - Operating system: Bullseye

**Comment by foxthefox** [comment]
Sorry für die späte Antwort, war im Urlaub. Werde mir das Problem dieses WE anschauen

**Comment by foxthefox** [comment]
habe auf github die Version 1.1.1 erstellt, bitte einmal testen und berichten.
Ich habe diverse loglevel geändert, beim Start gibt es nun Infos zum SerialPort.
Falls nichts danach passiert, bitte auf debug umstellen und berichten, was geloggt wird.

**Comment by tis-cs** [comment]
Ich habe nun auf 1.1.1 geupdated und jeweils einen Sensor mit der ID35 hinzugefügt. Im Log kommt leider immer noch nichts. Auch nicht, wenn man auf DEBUG stellt. Kann man sonst irgendwie unterstützen?

**Comment by foxthefox** [comment]
also die 3 Sensoren, die beispielhaft in der Konfiguration drin sind, kannst du löschen.
Dann ein neuen Sensor einfügen der meinetwegen die id und uid mit 35 und als type den LaCrosseDTH hat.
Dann nochmal in debug die Sache anschauen und ein wenig Zeit lassen (30min oder so), die Sensoren senden ja nicht jede Sekunde.
Dann sollte auch mal eine Meldung eingefangen werden.
Falls das mit dem neuen seriellen Treiber in 1.1.0/1.1.1 zusammenhängen sollte, dann bitte den Adapter löschen und 1.0.3 installieren und wieder die Konfiguration einstellen und im debug die Sache länger beobachten
und berichten

**Comment by tis-cs** [comment]
Wenn ich die 1.1.1 oder die 0.1.4 installiere, bekomme ich noch immer nichts im Log (Level egal). Jedoch werden unter beiden Versionen Objekte in ioBroker erzeugt, wenn ich den Sensor mit der ID35 manuell anlege. Somit bekomme ich zumindest einen Sensor ans laufen.

Jedoch kann ich so keinen 2. Sensor betreiben. Dieser liefert dann keine Werte. Wenn man in den Sensor reinhaucht, sendet er innerhalb von fünf Sekunden neue Daten, das geht ganz zuverlässig.

Wenn ich den Adapter bei ioBroker zuerst lösche und dann per Console mit `iobroker url https://github.com/foxthefox/ioBroker.jeelink` oder über das UI über die Github URL installiere, wird mir immer die aktuelle Instanz 1.1.1 installiert. In der Anzeige bei der Versionsauswahl sind immer nur die ganz alten Versionen aufgelistet.
<img width="561" alt="Bildschirm­foto 2022-12-11 um 23 22 31" src="https://user-images.githubusercontent.com/24519878/206933349-e9f29e4e-9d36-443f-9782-7de8bd739d1d.png">

Wie komme ich manuell an die 1.0.3? NPM mag er gar nicht... Ist aktuell ein Pi3B+

Danke!

**Comment by foxthefox** [comment]
1.0.3 ist schonmal gut, die funktioniert auch. War evtl. oben nicht ganz ersichtlich, das diese bei npm liegt, ist ja jetzt am laufen.
Ich weiß nichts von Änderungen beim logging.
Kannst du dennoch den debug modus einschalten (nicht nur im logging umschalten, sondern auch bei der Instanz) und dann neu starten.
Das log würde ich mir dann mal ansehen, da muß was drin stehen.
Welche FW ist denn auf dem Stick?

**Comment by tis-cs** [comment]
Ich traue es mich fast nicht zu sagen, aber es lag an mir und nicht am Adapter... Es laufen wohl alle Versionen (1.0.3 und 1.1.1 getestet). Ich hatte es nicht mehr auf dem Schirm, dass ich bei den Instanzen die jeweils installierte Instanz auch zuvor im Loglevel auf Debug stellen muss, damit im Protokoll auch unter Debug was auftaucht. Nun sehe ich dort beide Sensoren mit ihren ID's als undefinded, sofern dies noch nicht geschehen ist. Wenn man ihn dann hinzufügt kommen auch alle 5 Sekunden neue Daten rein und werden in den Objekten hinterlegt. Vielen Dank für deine Bemühungen. Ich poste es auch mal im Forum, damit andere vielleicht auch was davon haben. Danke und liebe Grüße!

PS: ich habe v.1.67 auf den Sticks geflasht. Ich dachte ich hätte einen mit 433MHz und einen mit 868MHz, wobei nun beide die TX29 empfangen, die mit 868MHz senden.
